import { ThatsMeDeck } from '@/lib/types';

export const everydayDeck: ThatsMeDeck = {
  id: 'everyday',
  name: 'Everyday Us',
  emoji: '☕',
  color: '#FFD93D',
  description: 'The little things that say a lot.',
  questions: [
    'Who takes longer to get ready?',
    'Who is the better cook?',
    'Who falls asleep first at night?',
    'Who is messier?',
    'Who talks more?',
    'Who drives better?',
    'Who is more stubborn?',
    'Who is funnier?',
    'Who wakes up earlier?',
    'Who spends more money eating out?',
    'Who remembers important dates better?',
    'Who is the better dancer?',
    'Who cries more easily at movies?',
    'Who is the better gift-giver?',
    'Who eats faster?',
    'Who is more patient?',
    'Who is more likely to get lost?',
    'Who is the better singer?',
    'Who apologises first after an argument?',
    'Who is the bigger worrier?',
    'Who makes friends more easily?',
    'Who is more adventurous with food?',
    'Who handles stress better?',
    'Who is more romantic?',
    'Who is the better planner?',
    'Who stays calmer in emergencies?',
    'Who is more likely to stay up past midnight?',
    'Who is better at saving money?',
    'Who is the better hugger?',
    'Who snores louder?',
  ],
};
