import { ThatsMeDeck } from '@/lib/types';

export const naijaLifeDeck: ThatsMeDeck = {
  id: 'naijalife',
  name: 'Naija Life',
  emoji: '🇳🇬',
  color: '#FF8FB1',
  description: 'Real life, Nigerian edition.',
  questions: [
    'Who would argue longest with an Okada driver over the price?',
    'Who finishes jollof rice the fastest?',
    'Who dresses better for an owambe?',
    'Who is more likely to show up late everywhere?',
    'Who can haggle better at the market?',
    'Who eats more pepper?',
    'Who knows more Nollywood movies?',
    'Who would survive a NEPA blackout without complaining?',
    'Who is more likely to fall asleep in church?',
    'Who cooks better egusi soup?',
    'Who has a longer contact list?',
    'Who spends more hours on Instagram?',
    'Who would win at ludo?',
    'Who handles family drama more calmly?',
    'Who knows more current Afrobeats songs?',
    'Who would thrive more in the village?',
    'Who is more generous when splitting bills?',
    'Who gives better advice?',
    'Who is more likely to cry at a Nollywood movie?',
    'Who has better street sense?',
    'Who would win an argument with a Lagos bus conductor?',
    'Who remembers more Yoruba proverbs?',
    'Who eats suya faster?',
    'Who is more likely to buy something they do not need at the market?',
    'Who greets elders more properly?',
    'Who is better at managing okro without making it slimy?',
    'Who would survive longer without their phone?',
    'Who is the better Aso-Ebi shopper?',
    'Who knows more celebrity gossip?',
    'Who would win a dance-off at an owambe?',
  ],
};
