import { HWDYKMDeck } from '@/lib/types';

export const everydayDeck: HWDYKMDeck = {
  id: 'everyday',
  name: 'Everyday Us',
  emoji: '☕',
  color: '#FFD93D',
  description: 'The questions you forget to ask.',
  questions: [
    "What's my comfort food when I am stressed?",
    "What's the first thing I do when I wake up?",
    "Which of my friends do I secretly find exhausting?",
    "What is my go-to street food when I am in a hurry?",
    "What show could I rewatch forever?",
    "What's my biggest pet peeve?",
    "What time do I actually want to go to bed?",
    "Which household chore do I hate most?",
    "What is the talent I have that most people do not know about?",
    "What do I do with my phone in the bathroom?",
    "What part of my morning routine could I never skip?",
    "What is the snack I always reach for when no one is watching?",
    "Which app do I spend the most time on?",
    "What is the one chore I secretly enjoy?",
    "How do I usually unwind after a long day?",
    "What is the small thing that always makes me smile?",
    "Which season feels most like me?",
    "What kind of weather puts me in the best mood?",
    "What is my real, honest opinion on small talk?",
    "What is one thing I have been quietly looking forward to?",
    "If I had a free Saturday with no plans, what would I actually do?",
    "What is my favorite way to eat eggs?",
    "Which family member do I sound most like?",
    "What is something small I do every day that I think no one notices?",
    "What is my honest relationship with mornings?",
    "How long do I actually spend on my phone before sleeping?",
    "What is my true feeling about sharing food on a date?",
    "What is the one thing I will never order at a restaurant?",
    "When I am upset, what do I actually need from the people close to me?",
    "What is the most embarrassing thing currently on my phone?",
    "What is something I judge people for but quietly do myself?",
    "What is the compliment I hear most often that I never fully believe?",
    "What is a habit I have that I know I should stop but have not?",
    "What is the food I could eat every day without getting tired of it?",
    "What is something I say I am fine about but am actually not fine about?",
    "What do I think about when I cannot sleep?",
    "What would I spend a random extra fifty thousand naira on?",
    "What is the first thing I notice when entering someone's house?",
    "What is a skill I have that most people do not know about?",
    "What is my honest opinion about surprise parties?",
    "What is one thing about my daily routine that secretly stresses me?",
    "What is my comfort show when I am sick?",
    "What is a habit I have that I hope people around me have not noticed?",
    "What is the best gift anyone has ever given me?",
    "What is one thing I wish I were better at?",
    "What is my honest opinion of Mondays?",
    "What is the purchase I regret most in the past year?",
    "What is the thing I would never admit to a stranger but would tell my partner?",
    "What is one thing that will always make me laugh no matter my mood?",
    "What is the meal I think about the most when I am far from home?",
    "What is the last thing I cried about?",
    "What is the first sign that I like someone without meaning to show it?",
    "What is my real opinion about working from home?",
    "What is something I find genuinely romantic that people might find odd?",
    "What is the thing I am most proud of that I never talk about?",
    "What does my ideal quiet Sunday look like from morning to night?",
    "What is something I have been meaning to learn but keep putting off?",
    "What is my honest relationship with money and saving?",
    "What is the one food rule I have that I refuse to break?",
    "What am I irrationally territorial about?",
    "What is something I do alone that I would be embarrassed to do in front of others?",
  ],
};
