import { HWDYKMDeck } from '@/lib/types';

export const everydayDeck: HWDYKMDeck = {
  id: 'everyday',
  name: 'Everyday Us',
  emoji: '☕',
  color: '#FFD93D',
  description: 'The questions you forget to ask.',
  questions: [
    "What's my comfort food when I am stressed?",
    "What's the first thing I do when I wake up?",
    "Which of my friends do I secretly find exhausting?",
    "What's my go-to drink order?",
    "What show could I rewatch forever?",
    "What's my biggest pet peeve?",
    "What time do I actually want to go to bed?",
    "Which household chore do I hate most?",
    "What's my karaoke song?",
    "What do I do with my phone in the bathroom?",
    "What part of my morning routine could I never skip?",
    "What is the snack I always reach for when no one is watching?",
    "Which app do I spend the most time on?",
    "What is the one chore I secretly enjoy?",
    "How do I usually unwind after a long day?",
    "What is the small thing that always makes me smile?",
    "Which season feels most like me?",
    "What kind of weather puts me in the best mood?",
    "What is my real, honest opinion on small talk?",
    "What is one thing I have been quietly looking forward to?",
    "If I had a free Saturday with no plans, what would I actually do?",
    "What is my favorite way to eat eggs?",
    "Which family member do I sound most like?",
    "What is the last thing I googled?",
    "What is something small I do every day that I think no one notices?",
  ],
};
