import { HWDYKMDeck } from '@/lib/types';

export const naijaLifeDeck: HWDYKMDeck = {
  id: 'naijalife',
  name: 'Naija Life',
  emoji: '🇳🇬',
  color: '#FF8FB1',
  description: 'The questions only your person can answer.',
  questions: [
    "What is my go-to Nigerian food when I need to feel at home?",
    "How do I really feel about japa and relocating abroad?",
    "What is the one Nigerian dish I could never live without?",
    "What is my honest opinion about Lagos traffic?",
    "What would I do on a free Sunday afternoon in a Nigerian city?",
    "What do I actually think about generator culture in Nigeria?",
    "How do I feel when NEPA suddenly restores power at night?",
    "What is the first thing I buy at a Nigerian party?",
    "What is my real opinion about aso-ebi and how much it costs?",
    "What type of jollof do I think is truly the best?",
    "How do I feel about Nigerian aunties and their unsolicited advice?",
    "What is my honest relationship with saving money versus spending it?",
    "What is my true opinion about owambe parties in Nigeria?",
    "Which Nigerian city do I think is the best place to live right now?",
    "How do I feel about the expectation to send money home to family?",
    "What is my go-to food order when I am in Lagos?",
    "How do I handle NEPA taking light when I am in the middle of something important?",
    "What is my honest feeling about Nigerian weddings and how long they last?",
    "What is the Nigerian TV show or movie that I always recommend?",
    "How do I feel about using OPay or Palmpay versus a traditional bank?",
    "What is my true feeling about early morning church or mosque attendance?",
    "What is my opinion on the pressure to own a car in Nigeria?",
    "How do I react when the POS machine says no network?",
    "What do I actually think about Nigerian street food?",
    "What is my real feeling about working in Nigeria versus abroad?",
    "How do I feel when I have to explain Nigerian culture to someone who does not get it?",
    "What is my favorite thing about Nigerians that I am genuinely proud of?",
    "What Nigerian habit or tradition do I think the world should know about?",
    "How do I handle a relative who always borrows money and never returns it?",
    "What is my honest opinion about the Nigerian education system?",
    "How do I feel about the naira and the dollar exchange rate situation?",
    "What is my real attitude toward Nigerian road safety and driving culture?",
    "What do I miss most about Nigeria when I am somewhere else?",
    "What is my favorite part of a traditional Nigerian celebration?",
    "How do I feel about the saying that things will be better in Nigeria?",
    "What is my honest take on Nigerian music and its global rise?",
    "What Nigerian slang do I use the most without even thinking?",
    "How do I feel about returning to my hometown for events and ceremonies?",
    "What is the one Nigerian meal I would cook for someone I was trying to impress?",
    "What is my honest feeling about the hustle culture that defines Lagos?",
    "How do I feel when I meet a fellow Nigerian in an unexpected place abroad?",
    "What is my favorite Nigerian snack and when do I reach for it most?",
    "What is my real opinion about doing business with family in Nigeria?",
    "How do I feel about the expectation to be the family success story?",
    "What is my go-to response when someone outside Nigeria asks what Nigeria is really like?",
    "What is something uniquely Nigerian about me that I love?",
    "How do I feel when someone makes a joke about Nigeria that I find unfair?",
    "What is my honest opinion about overnight buses in Nigeria?",
    "What is my ideal Nigerian retirement picture if everything went right?",
    "What is the one thing about Nigeria that gives me genuine hope for the future?",
  ],
};
