import { WMPRDeck } from '@/lib/types';

export const deepCutsDeck: WMPRDeck = {
  id: 'deepcuts',
  name: 'Deep Cuts',
  emoji: '🌙',
  color: '#A78BFA',
  description: 'Soft questions for quiet evenings.',
  questions: [
    ['Forget your happiest memory', 'Forget your saddest memory'],
    ['Be deeply understood by one person', 'Be liked by everyone you meet'],
    ['Travel anywhere alone', 'Stay home with the people you love'],
    ['Have your dream career and an average love life', 'Have an average career and a dream love life'],
    ['Always know what people really think of you', 'Never know what anyone thinks of you'],
    ['Be the funniest person in the room', 'Be the kindest person in the room'],
    ['Have one true calling', 'Be quietly good at many things'],
    ['Live where you grew up forever', 'Never go back home'],
    ['Be remembered after you die', 'Be deeply present while you live'],
    ['Have all the answers but no questions', 'Have all the questions but no answers'],
    ['Be the one who loves more', 'Be the one who is loved more'],
    ['Know your purpose at age 20', 'Find it slowly over many years'],
    ['Be brave for an hour a day', 'Be patient all the time'],
    ['Have a life full of small joys', 'Have a life with one great triumph'],
    ['Apologize to someone you wronged', 'Forgive someone who wronged you'],
    ['Always be slightly ahead of where you wanted to be', 'Always be slightly behind but enjoying the road'],
    ['Be the person who makes others feel seen', 'Be the person who is finally seen'],
    ['Take a leap and possibly fail', 'Stay safe and possibly wonder'],
    ['Be sure', 'Be open'],
    ['Have your parents fully approve of your partner', 'Have your closest friends fully approve of your partner'],
    ['Build a life abroad with everything you dreamed of but miss home deeply', 'Build a life in Nigeria with your people even when it is harder'],
    ['Be the child who relocated and built a new life', 'Be the child who stayed home and held the family together'],
    ['Have a stable government job with security but limited growth', 'Hustle in the private sector with more risk but more reward'],
    ['Have a quiet life with deep roots in one city', 'Have an adventurous life moving between cities and countries'],
    ['Know exactly what your family expects of you', 'Have complete freedom to define success for yourself'],
    ['Marry someone your family loves but who challenges you', 'Marry someone your family questions but who truly gets you'],
    ['Have a partner who is your best friend above all else', 'Have a partner who pushes you to become your best self'],
    ['Be financially comfortable but emotionally restless', 'Be financially uncertain but emotionally at peace'],
    ['Live in a home full of noise and family nearby', 'Live in a peaceful home with space and quiet'],
    ['Choose love over ambition when they conflict', 'Choose ambition over love when they conflict'],
    ['Raise children the traditional Nigerian way you were raised', 'Raise children with a completely different approach than your upbringing'],
    ['Have a mentor who changed your life completely', 'Find your own path alone and learn from every stumble'],
    ['Be deeply spiritual and draw strength from faith', 'Find your strength from within yourself and your own resilience'],
    ['Have a gift that comes naturally but earns you less', 'Have a skill you worked hard for that earns you more'],
    ['Spend a year in Lagos grinding at the peak of its chaos', 'Spend a year in a quiet smaller city finding yourself'],
    ['Be the one who always shows up for people even when tired', 'Be the one who has finally learned to set boundaries and rest'],
    ['Have a long-distance relationship that keeps the love strong', 'Be in the same city as your partner through all the small moments'],
    ['Live a loud, celebrated, public life', 'Live a quiet, intentional, private life'],
    ['Have the courage to say what you feel right when you feel it', 'Have the wisdom to know when silence is the kinder choice'],
    ['Let go of something you loved but outgrew', 'Hold on to something old that still gives you peace'],
    ['Be known for your work', 'Be known for your character'],
    ['Struggle and grow in your twenties with a great story to tell', 'Have a smooth road in your twenties with steady building'],
    ['Have one true friendship that outlasts everything', 'Have a wide circle of people who genuinely care about you'],
    ['Know that your relationship is the best thing in your life', 'Know that your relationship makes everything else feel possible'],
    ['Have the hard conversation now and feel the relief', 'Wait for the right moment and carry the weight a little longer'],
    ['Be the kind of person who plans everything carefully', 'Be the kind of person who adapts beautifully to whatever comes'],
    ['Leave something unfinished but move on', 'See everything through even when it costs you something'],
    ['Be deeply proud of where you come from', 'Be excited about where you are going'],
    ['Have your dream job find you', 'Chase your dream job with everything you have'],
    ['Choose rest when the world says push', 'Choose to push when everything in you wants to rest'],
    ['Be at peace with your past', 'Be excited about your future'],
  ],
};
