import { WMPRDeck } from '@/lib/types';

export const hotTakesDeck: WMPRDeck = {
  id: 'hottakes',
  name: 'Hot Takes',
  emoji: '🌶️',
  color: '#FF6B6B',
  description: 'Petty opinions, fully aired.',
  questions: [
    ['Pineapple belongs on pizza', 'Pineapple on pizza is a war crime'],
    ['Cereal is a soup', 'Cereal is its own thing, leave me alone'],
    ['Hot dogs are sandwiches', 'Hot dogs are tacos'],
    ['Texting "k" is fine', 'Texting "k" is hostile'],
    ['Socks with sandals is acceptable', 'Socks with sandals is a crime'],
    ['Movie theaters are still better than streaming', 'Streaming wins every time'],
    ['Plane window seat', 'Plane aisle seat (window people are wrong)'],
    ['Wedding registries are practical', 'Wedding registries are tacky'],
    ['Voice notes are efficient', 'Voice notes are a personal attack'],
    ['Group chats should be muted by default', 'Group chats should be loud and proud'],
    ['Bread should always be toasted', 'Toasting bread is overrated'],
    ['Cold pizza is better than hot pizza', 'Cold pizza is suffering'],
    ['Birthday parties for adults are sweet', 'Birthday parties for adults are tragic'],
    ['Reply-all is a useful tool', 'Reply-all should be illegal'],
    ['Always tip the delivery guy generously', 'Tipping culture has gone too far'],
    ['Phone calls beat texts every time', 'Phone calls without warning are rude'],
    ['Replying to a story with a single emoji is fine', 'Replying to a story with a single emoji is lazy'],
    ['Buffet restaurants are joyful', 'Buffet restaurants are deeply sad'],
    ['Decorating for Christmas before December is a sin', 'November Christmas trees are valid'],
    ['Brunch is overrated', 'Brunch is sacred'],
    ['Dogs are clearly better than cats', 'Cats are clearly better than dogs'],
    ['Owning a smart speaker is convenient', 'Smart speakers are spying on us'],
    ['Coffee is just bean water', 'Coffee is liquid serotonin'],
    ['Working from a cafe is productive', 'Working from a cafe is performance art'],
    ['Asking for the WiFi password before saying hello is acceptable', 'Asking for the WiFi password before saying hello is rude'],
  ],
};
