import { WMPRDeck } from '@/lib/types';

export const hotTakesDeck: WMPRDeck = {
  id: 'hottakes',
  name: 'Hot Takes',
  emoji: '🌶️',
  color: '#FF6B6B',
  description: 'Petty opinions, fully aired.',
  questions: [
    ['Pineapple belongs on pizza', 'Pineapple on pizza is a war crime'],
    ['Texting "k" is fine', 'Texting "k" is hostile'],
    ['Voice notes are efficient', 'Voice notes are a personal attack'],
    ['Group chats should be muted by default', 'Group chats should be loud and proud'],
    ['Cold pizza is better than hot pizza', 'Cold pizza is suffering'],
    ['Phone calls beat texts every time', 'Phone calls without warning are rude'],
    ['Dogs are clearly better than cats', 'Cats are clearly better than dogs'],
    ['Coffee is just bean water', 'Coffee is liquid serotonin'],
    ['Working from a cafe is productive', 'Working from a cafe is performance art'],
    ['Asking for the WiFi password before saying hello is acceptable', 'Asking for the WiFi password before saying hello is rude'],
    ['Nigerian jollof is the best jollof, end of discussion', 'Ghanaian jollof is underrated and deserves respect'],
    ['Lagos is the greatest city in Africa', 'Abuja is a better city to actually live in'],
    ['Japa is the smartest move any young Nigerian can make', 'Building your future in Nigeria takes more courage and matters more'],
    ['Aso-ebi is a beautiful tradition worth every kobo', 'Aso-ebi is a polite way of collecting money from friends'],
    ['Owambe parties are the best social invention ever', 'Owambe parties are exhausting and too long'],
    ['Pounded yam beats all other swallows', 'Eba is the real peoples swallow'],
    ['Nollywood has genuinely great films now', 'Nollywood still has a long way to go and we know it'],
    ['POS charges are stealing in plain sight', 'POS charges are fair given what operators go through'],
    ['Suya is better with bread', 'Suya must only be eaten plain with onion and tomato'],
    ['Fufu is the superior swallow', 'Amala is the most underrated swallow in Nigeria'],
    ['Generator culture has become too normalized', 'Generator culture is just Nigerians being resilient and adaptable'],
    ['Nigerian food is the best cuisine in Africa, full stop', 'Ghanaian food is more refined than most Nigerians will admit'],
    ['Jollof rice from outside Nigeria should never be called jollof', 'Any jollof made with love is valid jollof, regardless of country'],
    ['WhatsApp status is a legitimate form of communication', 'WhatsApp status is just a cry for attention'],
    ['Replying to a story with a single emoji is completely fine', 'Replying to a story with a single emoji is lazy and says nothing'],
    ['Church should not last more than two hours', 'Church should last as long as the Spirit leads, no question'],
    ['OPay is the future of Nigerian banking', 'Traditional banks like GTBank are still more trustworthy'],
    ['Sending a long voice note when you could just type is inconsiderate', 'Voice notes are more personal and deserve appreciation'],
    ['Abuja food is overpriced for what you get', 'Abuja food is better quality than Lagos food'],
    ['Lagos traffic is spiritual warfare and nothing less', 'Lagos traffic is manageable if you understand the patterns'],
    ['Nigerian aunties mean well even when they say too much', 'Nigerian aunties need to learn boundaries urgently'],
    ['Rice on Christmas is non-negotiable', 'Jollof at Christmas is more festive than anything else'],
    ['Side-hustles are more important than your nine-to-five now', 'A stable job is still the most reliable foundation to build on'],
    ['Buffet restaurants are joyful', 'Buffet restaurants are deeply sad'],
    ['Brunch is overrated', 'Brunch is sacred'],
    ['Owning a smart speaker is convenient', 'Smart speakers are listening and we are all in danger'],
    ['Streaming is better than cinema', 'Cinema is still the superior viewing experience'],
    ['Reply-all should be illegal in corporate emails', 'Reply-all is a useful tool when used correctly'],
    ['Birthday parties for adults are sweet', 'Birthday parties for adults are increasingly unnecessary'],
    ['Always tip your delivery rider generously', 'Tipping culture is becoming a manipulation tactic'],
    ['Nigerian time is a cultural feature not a flaw', 'Nigerian time is a habit we need to collectively break'],
    ['Saving in dollars is smarter than saving in naira right now', 'Investing locally is more impactful even if the naira is weak'],
    ['Nigerian weddings are too expensive and too long', 'Nigerian weddings are a once-in-a-lifetime celebration worth every naira'],
    ['Banga soup is the most underrated Nigerian soup', 'Egusi is and always will be the king of Nigerian soups'],
    ['Pepper soup is a cure for everything', 'Pepper soup is overrated comfort food'],
    ['Small chops at a party are more important than the main food', 'Small chops are a distraction from the real jollof'],
    ['A career in tech is the safest path in Nigeria right now', 'Creative industries in Nigeria are the real untapped goldmine'],
    ['Nollywood romance movies are better than Hollywood ones', 'Hollywood romance movies still set the standard globally'],
    ['Having a car in Lagos is overrated given the traffic', 'Having a car in Lagos is still freedom regardless of traffic'],
    ['MTN has the best network in Nigeria by far', 'Airtel has quietly become the most reliable network now'],
    ['WhatsApp family groups should have a bedtime', 'WhatsApp family groups are how you stay connected and they are fine'],
    ['Men should ask for directions when lost', 'Men asking for directions is always the right call, not pride'],
    ['Parties should end by midnight no matter how good the vibes are', 'A party that ends before dawn was never really a party'],
    ['Garri and groundnut is a complete meal and not a snack', 'Garri and groundnut is a snack and we should not pretend otherwise'],
    ['Bole and fish is one of the most underrated Nigerian meals', 'Bole and fish is overrated and you can get better elsewhere'],
    ['Nigerian breakfast does not get enough international credit', 'Akara and agege bread might be the greatest breakfast combo ever'],
    ['Kuda Bank is the best bank in Nigeria right now', 'Moniepoint is quietly running things in Nigerian fintech now'],
    ['Going to the village for Christmas is nostalgic and irreplaceable', 'Staying in the city for Christmas is simply the more practical choice'],
    ['Praising the chef loudly is proper appreciation', 'Praising the chef is unnecessary if the food speaks for itself'],
    ['Window seat on a bus beats aisle seat every time', 'Aisle seat on a bus is always more practical'],
    ['Cereal is technically a soup', 'Cereal is its own category, please stop this discussion'],
    ['Semo is an acceptable substitute for pounded yam', 'Nothing substitutes real pounded yam, semo is not the same'],
    ['Nigerian tech startups are going to change Africa', 'Nigerian tech startups are mostly fixing problems that should not exist'],
    ['Nkwobi is a delicacy', 'Nkwobi is just an excuse to charge extra at the restaurant'],
    ['Zobo is one of the best cold drinks in the world', 'Chapman is the superior Nigerian party drink'],
  ],
};
