import { WMPRDeck } from '@/lib/types';

export const hypotheticalDeck: WMPRDeck = {
  id: 'hypothetical',
  name: 'Big Hypotheticals',
  emoji: '🌪️',
  color: '#FF8FB1',
  description: 'Real questions disguised as games.',
  questions: [
    ['Read minds, but only of strangers', 'Be invisible, but only when alone'],
    ['Live 200 years as yourself', 'Live 5 lives of 70 years each with no memory between'],
    ['Win the lottery but lose your sense of taste', 'Stay broke but taste food in HD'],
    ['Know exactly how you die', 'Know exactly when you die'],
    ['Teleport but only to places you have been before', 'Fly but only as fast as you can run'],
    ['Speak every language but forget your native one', 'Stay exactly as you are now'],
    ['Have unlimited money but zero privacy', 'Have unlimited privacy but an average income'],
    ['Be famous for something embarrassing', 'Be unknown but legendary in your field'],
    ['Always know when someone is lying', 'Always know when someone is in love'],
    ['Live one perfect day on repeat', 'Live a normal varied life'],
    ['Remember every dream you ever had', 'Remember every meal you ever ate'],
    ['Be able to undo any one moment in your life', 'Be able to relive any one moment in your life'],
    ['Have a perfectly accurate memory', 'Have a perfect imagination'],
    ['Always be five minutes early everywhere', 'Always have five extra minutes when you need them'],
    ['Know what every animal is thinking', 'Know what every baby is thinking'],
    ['Have your dream career and average love life', 'Have an average career and dream love life'],
    ['Live anywhere in the world but never see your family', 'Live near your family but never travel'],
    ['Be the smartest person in every room', 'Be the kindest person in every room'],
    ['Know the answer to one big question (you pick)', 'Know the answer to a hundred small ones'],
    ['Have a guaranteed soulmate but you have to find them', 'Build something great with someone good enough'],
    ['Be able to pause time for one hour a day', 'Be able to rewind time for one minute a day'],
    ['Have a magic mirror that tells you the truth', 'Have a magic notebook that writes back'],
    ['Always say the right thing', 'Always know the right thing to do'],
    ['Be loved deeply by one person', 'Be liked warmly by everyone'],
    ['Have generator fuel that never runs out', 'Have NEPA restore stable power permanently to your house'],
    ['Japa to any country of your choice with a guaranteed visa', 'Get a guaranteed breakthrough that lets you build your dream life in Nigeria'],
    ['Have any skill you want but you can only use it in Nigeria', 'Have any skill you want but you must move abroad to use it'],
    ['Be the richest person in your state but nobody knows', 'Be known as successful but only earning comfortably'],
    ['Never sit in Lagos traffic again but you must use danfo only', 'Drive your own car in Lagos but traffic remains exactly as it is'],
    ['Have a business that runs itself while you sleep', 'Have a career that energizes you but demands your full attention'],
    ['Know the winning lotto numbers but only once', 'Know which business idea will succeed before starting it'],
    ['Have every Nigerian bank waive all your fees forever', 'Have the dollar exchange rate freeze in your favor forever'],
    ['Live in a world where NEPA never fails', 'Live in a world where fuel scarcity never happens again'],
    ['Build a house in your village and never want for anything', 'Build a flat in Lagos and hustle for everything'],
    ['Have your family fully support any career you choose', 'Have your family push back but the career succeeds beyond expectations'],
    ['Work for yourself from day one even in difficult years', 'Work for someone else for ten years and launch with perfect timing'],
    ['Speak fluent Yoruba, Igbo, and Hausa in addition to English', 'Speak fluent French, Mandarin, and Arabic in addition to English'],
    ['Retire at 40 in Lagos with enough to be comfortable', 'Retire at 60 abroad with more than enough and total security'],
    ['Have every person you love healthy and happy but you struggle', 'Have everything you want personally but one person you love is going through something hard'],
    ['Be known as the person who changed your family tree', 'Be known as the person who lived a beautiful, peaceful life'],
    ['Have one viral moment that opens every door for a year', 'Have a slow consistent rise that builds an unshakeable foundation'],
    ['Own a plot of land in Lekki now while prices are rising', 'Own a fully finished property in a mid-level area now'],
    ['Have every app on your phone work perfectly with no lag forever', 'Have your internet connection at maximum speed everywhere in Nigeria'],
    ['Know which investments will double in value this year', 'Know which skills will be most valuable in Nigeria in ten years'],
    ['Have a Nigerian passport that gets visa-free entry everywhere', 'Have an EU passport but you must renounce your Nigerian one'],
    ['Have a business partner who is brilliant but difficult', 'Have a business partner who is steady and easy to work with'],
    ['Get your dream job in your dream company starting tomorrow', 'Start your own thing with the right co-founder starting tomorrow'],
    ['Have a mentor who is strict and changes your life', 'Figure it out yourself and learn from the experience'],
    ['Live in the era when Nigeria finally gets it right', 'Leave the country before things turn around and miss the renaissance'],
    ['Be a big fish in a small Nigerian pond', 'Be a small fish in a global ocean'],
    ['Have every contract you sign be honoured always', 'Have every person you trust with money return it always'],
    ['Win a government contract that changes your life', 'Win a private sector deal that changes your life'],
    ['Travel to every African country in one year all expenses paid', 'Travel to ten countries outside Africa in one year all expenses paid'],
    ['Have your Nigerian startup raise dollar funding', 'Have your Nigerian startup profitable from day one in naira'],
    ['Have unlimited data with full network coverage everywhere', 'Have the ability to work from anywhere in Nigeria without power cuts'],
    ['Inherit land in a growing part of Nigeria', 'Inherit a business that is already profitable'],
    ['Build your dream home in Abuja', 'Build your dream home in Lagos'],
    ['Have a long holiday in Zanzibar fully paid', 'Have a long holiday anywhere in Nigeria you have never been fully paid'],
    ['Start over at 25 with everything you know now', 'Stay exactly where you are now with exactly what you know'],
    ['Have your relationship celebrated publicly by your community', 'Have a private love that needs no outside validation ever'],
    ['Be completely honest with everyone in your life for one year', 'Be completely kind even when honesty would be the harder choice'],
  ],
};
