import { WMPRDeck } from '@/lib/types';

export const hypotheticalDeck: WMPRDeck = {
  id: 'hypothetical',
  name: 'Big Hypotheticals',
  emoji: '🌪️',
  color: '#FF8FB1',
  description: 'Real questions disguised as games.',
  questions: [
    ['Read minds, but only of strangers', 'Be invisible, but only when alone'],
    ['Live 200 years as yourself', 'Live 5 lives of 70 years each with no memory between'],
    ['Win the lottery but lose your sense of taste', 'Stay broke but taste food in HD'],
    ['Know exactly how you die', 'Know exactly when you die'],
    ['Teleport but only to places you have been before', 'Fly but only as fast as you can run'],
    ['Speak every language but forget your native one', 'Stay exactly as you are now'],
    ['Have unlimited money but zero privacy', 'Have unlimited privacy but an average income'],
    ['Be famous for something embarrassing', 'Be unknown but legendary in your field'],
    ['Always know when someone is lying', 'Always know when someone is in love'],
    ['Live one perfect day on repeat', 'Live a normal varied life'],
    ['Remember every dream you ever had', 'Remember every meal you ever ate'],
    ['Be able to undo any one moment in your life', 'Be able to relive any one moment in your life'],
    ['Have a perfectly accurate memory', 'Have a perfect imagination'],
    ['Always be five minutes early everywhere', 'Always have five extra minutes when you need them'],
    ['Know what every animal is thinking', 'Know what every baby is thinking'],
    ['Have your dream career and average love life', 'Have an average career and dream love life'],
    ['Live anywhere in the world but never see your family', 'Live near your family but never travel'],
    ['Be the smartest person in every room', 'Be the kindest person in every room'],
    ['Know the answer to one big question (you pick)', 'Know the answer to a hundred small ones'],
    ['Have a guaranteed soulmate but you have to find them', 'Build something great with someone good enough'],
    ['Be guaranteed to be remembered after you die', 'Be guaranteed to be present while you live'],
    ['Be able to pause time for one hour a day', 'Be able to rewind time for one minute a day'],
    ['Have a magic mirror that tells you the truth', 'Have a magic notebook that writes back'],
    ['Always say the right thing', 'Always know the right thing to do'],
    ['Be loved deeply by one person', 'Be liked warmly by everyone'],
  ],
};
