import { WMPRDeck } from '@/lib/types';

export const sillyDeck: WMPRDeck = {
  id: 'silly',
  name: 'Silly Street',
  emoji: '🎪',
  color: '#FFD93D',
  description: 'Cartoon logic, no consequences.',
  questions: [
    ['Fight 100 chicken-sized horses', 'Fight 1 horse-sized chicken'],
    ['Sneeze glitter forever', 'Cry tears that taste like Coke'],
    ['Have fingers as long as your legs', 'Have legs as short as your fingers'],
    ['Speak only in rhyme for a year', 'Sing every sentence for a year'],
    ['Have a tail you cannot hide', 'Have ears that wiggle whenever you lie'],
    ['Always smell faintly of fresh bread', 'Always hear distant accordion music'],
    ['Have a permanent cartoon halo', 'Have a tiny rain cloud above you indoors only'],
    ['Sweat maple syrup', 'Cry hot pepper sauce'],
    ['Be three feet tall forever', 'Be eight feet tall forever'],
    ['Have hiccups for life', 'Yawn every sixty seconds for life'],
    ['Have a built-in laugh track that follows you', 'Have a dramatic violin sting after every sentence'],
    ['Be able to talk to pigeons (they are mean)', 'Be able to talk to plants (they are bored)'],
    ['Have hair that grows one inch every time you lie', 'Have nails that grow one inch every time you gossip'],
    ['Burp glitter', 'Sneeze rose petals'],
    ['Have feet that squeak when you walk', 'Have hands that beep when you point'],
    ['Be allergic to your own laughter', 'Be allergic to compliments'],
    ['Have one finger that glows in the dark', 'Have one tooth that always whistles'],
    ['Have your shadow be a different animal each day', 'Have your reflection always be three seconds late'],
    ['Wake up every day in a slightly different bed', 'Wake up every day with a slightly different name'],
    ['Have a sneeze that sounds like a goose', 'Have a cough that sounds like a kazoo'],
    ['Always lose at rock paper scissors', 'Always win at coin tosses but suspiciously'],
    ['Have your phone always autocorrect to "lasagna"', 'Have your phone always autocorrect to "wahala"'],
    ['Have one eyebrow that lifts uncontrollably', 'Have one finger that points wherever it wants'],
    ['Be the world champion at thumb wrestling but no one cares', 'Be the world champion at staring contests but for two seconds'],
    ['Have a song stuck in your head forever (you pick)', 'Have a different song stuck in your head every day (random)'],
    ['Have your dreams broadcast on a small TV in your living room', 'Have your thoughts whispered by a polite ghost'],
    ['Be the only person who can see one extra color', 'Be the only person who can hear one extra note'],
    ['Have a small cloud follow you that rains only on Tuesdays', 'Have a small sun follow you that shines only at 3am'],
    ['Have to clap before entering any room', 'Have to bow slightly when leaving any room'],
    ['Have a pocket that always has one wet sock in it', 'Have a pocket that always has one warm bean in it'],
    ['Have the worlds best impressions but only of furniture', 'Have the worlds best karaoke voice but only for national anthems'],
    ['Have your handshake play a tiny fanfare', 'Have your hug make a soft popcorn sound'],
    ['Always know what time it is to the exact second (annoyingly)', 'Always know the temperature to the exact degree (uselessly)'],
    ['Be irresistibly drawn to fold every towel you see', 'Be irresistibly drawn to align every book you see'],
    ['Have a tiny invisible duck that quacks when you lie', 'Have a tiny invisible cat that purrs when you are right'],
    ['Be slightly damp at all times', 'Be slightly dusty at all times'],
    ['Have your sneezes echo for thirty seconds', 'Have your laughs echo for one minute'],
    ['Be physically incapable of whispering', 'Be physically incapable of shouting'],
    ['Have a soundtrack that swells whenever you enter a room', 'Have a record-scratch sound every time you change your mind'],
    ['Be served jollof at every conference you attend forever', 'Be served fried rice at every meeting you attend forever'],
    ['Have your dreams written and directed by a B-movie crew', 'Have your dreams scored by a frantic jazz trio'],
    ['Have a permanent confetti trail when you walk', 'Have a permanent applause track when you sit'],
    ['Be physically unable to enter a room without doing jazz hands', 'Be physically unable to leave a room without taking a bow'],
    ['Eat only jollof rice for one year', 'Eat only fried rice for one year'],
    ['Have NEPA take your light during a final match', 'Have NEPA take your light during your favorite movie'],
    ['Your generator only starts when you sing to it', 'Your generator runs on only tears of embarrassment'],
    ['Speak only Pidgin to your lecturer', 'Speak only formal English at a suya spot'],
    ['Your full name is announced by a praise singer at every office meeting', 'Your village nickname goes viral on Twitter'],
    ['Have your WhatsApp family group chat turned into a live show', 'Be made permanent admin of a 300-person church WhatsApp group'],
    ['Have suya that is always cold but perfectly spiced', 'Have hot suya that is never spiced enough'],
    ['Your okada always arrives early but takes the longest route', 'Your Uber keeps canceling but sends a new one instantly'],
    ['Be called aunty or uncle by every child you meet forever', 'Have strangers add Senior before your name at all times'],
    ['Speak only in Yoruba proverbs when giving advice', 'Speak only in Igbo proverbs when expressing emotions'],
    ['Have a phone that overheats but never dies', 'Have a phone that stays cool but always needs charging'],
    ['Your data finishes every time something important is loading', 'Your signal drops every time you make an important call'],
    ['Have morning devotion that lasts exactly one hour every day', 'Have Sunday service that ends exactly when your food is ready'],
    ['Miss a party because of traffic on Third Mainland Bridge', 'Arrive at a party and realize you have the wrong date'],
    ['Be the one who divides the meat at family dinner', 'Be the one who leads the blessing at every family meal'],
    ['Have your clothes always ironed but wrinkled after one wear', 'Have your clothes never wrinkle but shrink every wash'],
    ['Your generator runs on positive vibes only', 'NEPA restores power only when you are already asleep'],
    ['Win any argument by quoting a proverb nobody can verify', 'Settle any dispute by calling the eldest person in the room'],
    ['Only eat suya with bread always', 'Only eat suya with raw onion and pepper always'],
    ['Have pepper soup that always needs more pepper', 'Have pepper soup that is always slightly too peppery'],
    ['Have your phone autocorrect to "abi" in every language', 'Have your phone autocorrect to "sha" at the end of every sentence'],
    ['Have to say "ehen" after every sentence forever', 'Have to say "abeg" before every request forever'],
    ['Arrive one hour late to everything because African Time', 'Arrive one hour early and wait awkwardly at every event'],
    ['Have an auntie comment on your weight at every family gathering', 'Have a distant uncle ask when you are getting married at every event'],
    ['Be unable to pass akara without buying some', 'Be unable to pass suya without stopping always'],
    ['Travel Lagos to Abuja only by bus but it always runs on time', 'Travel Lagos to Abuja only by air but the flight always delays'],
    ['Have agege bread for breakfast every single day forever', 'Have indomie for lunch every single day forever'],
    ['Have a POS machine that always has network but never has cash', 'Have an ATM that always has cash but never has light'],
    ['Be followed by the smell of fresh bole and fish everywhere', 'Be followed by the smell of fresh fried akara everywhere'],
    ['Have your phone warn you at 10 percent at every critical moment', 'Have your charger only work when held at one specific angle'],
    ['Have your bank alert arrive three hours after every transaction', 'Have your OTP expire before you can use it every time'],
    ['Your boli always needs groundnut paste that is never there', 'Your shawarma always needs more sauce that never comes'],
    ['Have a Bluetooth speaker that only plays gospel on Sundays', 'Have a speaker that plays Afrobeats at the wrong volume always'],
    ["Your neighbor's generator sounds like a lullaby", "Your neighbor's generator sounds like a war drum at 2am"],
    ['Be unable to leave a party without being given food to take home', 'Be unable to arrive at a party without being given an assignment'],
    ['Your garri always needs one more cup of cold water', 'Your eba always needs one more stir before it is ready'],
    ['Have a PiggyVest that only saves when you are not looking', 'Have a Cowrywise that only invests during load shedding'],
    ['Be the one who fetches water whenever NEPA takes light', 'Be the one who refuels the generator every single time'],
    ['Have an auntie praise you for every small thing at church', 'Have an uncle remind you of every mistake at every naming ceremony'],
    ['Always have the last biscuit in the pack (it is always broken)', 'Always have the middle slice of bread (it is always the best)'],
    ['Have your MTN data finish during a video call always', 'Have your Airtel network disappear at every crowded venue'],
    ['Be slightly pepper-mouthed after every meal forever', 'Be slightly full before every meal ends forever'],
    ['Have your alarm only work when you are already awake', 'Have your alarm never work when you actually need it'],
    ['Only be able to receive cash but never transfer', 'Only be able to transfer but never receive cash'],
    ['Have your food somehow always need more salt after serving', 'Have your food always need more pepper after the first bite'],
    ['Have a fashion sense that is perfect but always one season late', 'Have a fashion sense that is always ahead but nobody gets it yet'],
    ['Be unable to take a photo without someone walking into the frame', 'Be unable to post a photo without someone tagging you in the comments'],
    ['Have your rechargeable lamp always run out at the worst moment', 'Have your power bank reach zero just when your phone hits five percent'],
    ['Only eat from plastic plates but they are always clean', 'Only eat from china plates but they are always slightly chipped'],
    ['Have all your selfies slightly blurry but the lighting is perfect', 'Have all your selfies perfectly sharp but the lighting is always off'],
  ],
};
