import { WMPRDeck } from '@/lib/types';

export const sillyDeck: WMPRDeck = {
  id: 'silly',
  name: 'Silly Street',
  emoji: '🎪',
  color: '#FFD93D',
  description: 'Cartoon logic, no consequences.',
  questions: [
    ['Fight 100 chicken-sized horses', 'Fight 1 horse-sized chicken'],
    ['Sneeze glitter forever', 'Cry tears that taste like Coke'],
    ['Have fingers as long as your legs', 'Have legs as short as your fingers'],
    ['Speak only in rhyme for a year', 'Sing every sentence for a year'],
    ['Have a tail you cannot hide', 'Have ears that wiggle whenever you lie'],
    ['Always smell faintly of fresh bread', 'Always hear distant accordion music'],
    ['Have a permanent cartoon halo', 'Have a tiny rain cloud above you indoors only'],
    ['Sweat maple syrup', 'Cry hot pepper sauce'],
    ['Be three feet tall forever', 'Be eight feet tall forever'],
    ['Have hiccups for life', 'Yawn every sixty seconds for life'],
    ['Have a built-in laugh track that follows you', 'Have a dramatic violin sting after every sentence'],
    ['Be able to talk to pigeons (they are mean)', 'Be able to talk to plants (they are bored)'],
    ['Have hair that grows one inch every time you lie', 'Have nails that grow one inch every time you gossip'],
    ['Burp glitter', 'Sneeze rose petals'],
    ['Have a mustache made of bees (gentle)', 'Have eyebrows made of butterflies (clingy)'],
    ['Be followed by gentle harp music wherever you go', 'Have a personal narrator describe your every move'],
    ['Have feet that squeak when you walk', 'Have hands that beep when you point'],
    ['Be allergic to your own laughter', 'Be allergic to compliments'],
    ['Have one finger that glows in the dark', 'Have one tooth that always whistles'],
    ['Speak fluent baby talk to all adults', 'Speak only in formal Shakespearean to babies'],
    ['Have your shadow be a different animal each day', 'Have your reflection always be three seconds late'],
    ['Wake up every day in a slightly different bed', 'Wake up every day with a slightly different name'],
    ['Have a sneeze that sounds like a goose', 'Have a cough that sounds like a kazoo'],
    ['Always lose at rock paper scissors', 'Always win at coin tosses but suspiciously'],
    ['Have your phone always autocorrect to "lasagna"', 'Have your phone always autocorrect to "wahala"'],
    ['Have one eyebrow that lifts uncontrollably', 'Have one finger that points wherever it wants'],
    ['Be the world champion at thumb wrestling but no one cares', 'Be the world champion at staring contests but for two seconds'],
    ['Have a song stuck in your head forever (you pick)', 'Have a different song stuck in your head every day (random)'],
    ['Walk three feet behind yourself at all times', 'Walk three feet ahead of yourself at all times'],
    ['Have your dreams broadcast on a small TV in your living room', 'Have your thoughts whispered by a polite ghost'],
    ['Be the only person who can see one extra color', 'Be the only person who can hear one extra note'],
    ['Have a small cloud follow you that rains only on Tuesdays', 'Have a small sun follow you that shines only at 3am'],
    ['Have to clap before entering any room', 'Have to bow slightly when leaving any room'],
    ['Have a pocket that always has one wet sock in it', 'Have a pocket that always has one warm bean in it'],
    ['Be the worlds best at impressions but only of furniture', 'Be the worlds best at karaoke but only of national anthems'],
    ['Have your handshake play a tiny fanfare', 'Have your hug make a soft popcorn sound'],
    ['Always know what time it is to the exact second (annoyingly)', 'Always know the temperature to the exact degree (uselessly)'],
    ['Be irresistibly drawn to fold every towel you see', 'Be irresistibly drawn to align every book you see'],
    ['Have a tiny invisible duck that quacks when you lie', 'Have a tiny invisible cat that purrs when you are right'],
    ['Be slightly damp at all times', 'Be slightly dusty at all times'],
    ['Have a sense of taste that ranks everything from one to ten out loud', 'Have a sense of smell that names every scent dramatically'],
    ['Have your sneezes echo for thirty seconds', 'Have your laughs echo for one minute'],
    ['Be physically incapable of whispering', 'Be physically incapable of shouting'],
    ['Have a soundtrack that swells whenever you enter a room', 'Have a record-scratch sound every time you change your mind'],
    ['Be able to fold space but only inside your fridge', 'Be able to fold time but only inside your shower'],
    ['Have a parrot on your shoulder that only speaks finance', 'Have a hamster in your pocket that only speaks Latin'],
    ['Be served cake at every meeting you attend forever', 'Be served jollof at every conference you attend forever'],
    ['Have your dreams written and directed by a B-movie crew', 'Have your dreams scored by a frantic jazz trio'],
    ['Have a permanent confetti trail when you walk', 'Have a permanent applause track when you sit'],
    ['Be physically unable to enter a room without doing jazz hands', 'Be physically unable to leave a room without taking a bow'],
  ],
};
