import { TriviaDeck } from '@/lib/types';

export const naijaTriviaDeck: TriviaDeck = {
  id: 'naija',
  name: 'Naija Vibes',
  emoji: '🦅',
  color: '#FF8C00',
  description: 'How well do you know your country?',
  questions: [
    { q: 'What is the capital city of Nigeria?', options: ['Lagos', 'Abuja', 'Kano', 'Ibadan'], answer: 1 },
    { q: 'In what year did Nigeria gain independence from Britain?', options: ['1955', '1957', '1960', '1963'], answer: 2 },
    { q: 'Nigeria has how many states?', options: ['30', '34', '36', '40'], answer: 2 },
    { q: 'Who wrote the novel "Things Fall Apart"?', options: ['Wole Soyinka', 'Chimamanda Adichie', 'Chinua Achebe', 'Ben Okri'], answer: 2 },
    { q: 'Which Nigerian won the Nobel Prize in Literature in 1986?', options: ['Chinua Achebe', 'Wole Soyinka', 'Ken Saro-Wiwa', 'Chimamanda Adichie'], answer: 1 },
    { q: 'What is the official language of Nigeria?', options: ['Yoruba', 'Hausa', 'Igbo', 'English'], answer: 3 },
    { q: 'What is the currency of Nigeria?', options: ['Cedi', 'Naira', 'Shilling', 'Franc'], answer: 1 },
    { q: 'Nigeria is the most populous country in which continent?', options: ['The world', 'Africa', 'West Africa', 'Sub-Saharan Africa'], answer: 1 },
    { q: 'The Nigerian national football team is called what?', options: ['Golden Eagles', 'Super Falcons', 'Super Eagles', 'Green Eagles'], answer: 2 },
    { q: 'Which lake is shared by Nigeria, Niger, Chad, and Cameroon?', options: ['Lake Victoria', 'Lake Volta', 'Lake Chad', 'Lake Tanganyika'], answer: 2 },
    { q: 'Nollywood is generally considered the world\'s second largest film industry by output. Which is first?', options: ['Hollywood', 'Bollywood', 'Chinese cinema', 'Korean cinema'], answer: 1 },
    { q: 'Which Nigerian city is known as "The Centre of Excellence"?', options: ['Abuja', 'Kano', 'Lagos', 'Port Harcourt'], answer: 2 },
    { q: 'Nigeria shares a land border with how many countries?', options: ['3', '4', '5', '6'], answer: 1 },
    { q: 'What does the green on the Nigerian flag represent?', options: ['The forests of Nigeria', 'Agriculture and natural wealth', 'Peace', 'The Niger River'], answer: 1 },
    { q: 'Which river is the longest river entirely within Nigeria?', options: ['Niger River', 'Benue River', 'Kaduna River', 'Ogun River'], answer: 0 },
    { q: 'The city of Kano is known for its ancient what?', options: ['Pyramids', 'Walls', 'Temples', 'Markets'], answer: 1 },
    { q: 'Which Nigerian city is the center of the oil industry?', options: ['Lagos', 'Abuja', 'Port Harcourt', 'Warri'], answer: 2 },
    { q: 'Chimamanda Ngozi Adichie is best known for which book?', options: ['Purple Hibiscus', 'Americanah', 'Half of a Yellow Sun', 'All of the above'], answer: 3 },
    { q: 'Aliko Dangote is known as what in Africa?', options: ['The richest man in Africa', 'The richest man in Nigeria', 'A Nigerian senator', 'A Nollywood producer'], answer: 0 },
    { q: 'The Osun-Osogbo Sacred Grove is a UNESCO World Heritage Site in which Nigerian state?', options: ['Lagos', 'Oyo', 'Osun', 'Ekiti'], answer: 2 },
    { q: 'In which year did Nigeria officially move its capital from Lagos to Abuja?', options: ['1985', '1991', '1993', '1999'], answer: 1 },
    { q: 'What language is widely spoken in Yorubaland?', options: ['Hausa', 'Igbo', 'Yoruba', 'Fulani'], answer: 2 },
    { q: 'Which Nigerian state is often called "the food basket of the nation"?', options: ['Benue', 'Plateau', 'Kebbi', 'Kogi'], answer: 0 },
    { q: 'The Eko Atlantic City is being built off the coast of which city?', options: ['Abuja', 'Port Harcourt', 'Lagos', 'Calabar'], answer: 2 },
    { q: 'Nigeria won its first Olympic gold medal in which sport?', options: ['Boxing', 'Football', '100 metres', 'Long jump'], answer: 1 },
    { q: 'Which traditional dish is commonly associated with the Igbo culture?', options: ['Tuwo Shinkafa', 'Ofe Akwu', 'Amala', 'Tuwon Masara'], answer: 1 },
    { q: 'What is the Nigerian slang "eba" made from?', options: ['Yam flour', 'Cassava flour', 'Corn flour', 'Plantain flour'], answer: 1 },
    { q: 'The city often called the ancient city of the Fulani in Nigeria is?', options: ['Kaduna', 'Sokoto', 'Jos', 'Maiduguri'], answer: 1 },
    { q: 'Nigeria was colonized by which European country?', options: ['France', 'Portugal', 'Britain', 'Germany'], answer: 2 },
    { q: 'What is the main ingredient in puff puff?', options: ['Cassava flour', 'Plantain', 'Wheat flour', 'Cornmeal'], answer: 2 },
    { q: 'Which Nigerian state is known for producing the most cocoa?', options: ['Osun', 'Ondo', 'Ogun', 'Cross River'], answer: 1 },
    { q: 'What is the name of the largest market in Lagos?', options: ['Alaba', 'Balogun', 'Idumota', 'Mile 12'], answer: 1 },
    { q: 'Who was Nigeria\'s first Prime Minister at independence?', options: ['Nnamdi Azikiwe', 'Aguiyi-Ironsi', 'Tafawa Balewa', 'Obafemi Awolowo'], answer: 2 },
    { q: 'The Nigerian civil war is also known as what?', options: ['The Delta War', 'The Biafra War', 'The Northern Conflict', 'The Oil War'], answer: 1 },
    { q: 'What is suya typically made from?', options: ['Pork', 'Chicken or beef', 'Fish', 'Goat meat'], answer: 1 },
    { q: 'The popular Nigerian drama "Jenifa\'s Diary" stars which actress?', options: ['Genevieve Nnaji', 'Omotola Jalade', 'Mercy Johnson', 'Funke Akindele'], answer: 3 },
    { q: 'Nigeria\'s first indigenous commercial bank was?', options: ['First Bank of Nigeria', 'African Continental Bank', 'United Bank for Africa', 'Access Bank'], answer: 1 },
    { q: 'What is "jollof" rice typically cooked in?', options: ['Plain water', 'Tomato and pepper base', 'Coconut milk', 'Vegetable stock only'], answer: 1 },
    { q: 'Which Nigerian state is nicknamed "the Sunshine State"?', options: ['Lagos', 'Osun', 'Ondo', 'Oyo'], answer: 2 },
    { q: 'Which of these is a Nigerian pidgin phrase meaning "no wahala" in English?', options: ['No stress', 'No problem', 'It is fine', 'All three are correct'], answer: 3 },
  ],
};
