import { TriviaDeck } from '@/lib/types';

export const weirdTriviaDeck: TriviaDeck = {
  id: 'weird',
  name: 'Weird and Wonderful',
  emoji: '🦑',
  color: '#A78BFA',
  description: 'Facts that sound made up.',
  questions: [
    { q: 'How many hearts does an octopus have?', options: ['1', '2', '3', '4'], answer: 2 },
    { q: 'What color is a polar bear\'s skin under its fur?', options: ['White', 'Pink', 'Black', 'Grey'], answer: 2 },
    { q: 'Which animal can sleep for up to three years at a time?', options: ['Bear', 'Snail', 'Sloth', 'Bat'], answer: 1 },
    { q: 'What is the only food that never spoils?', options: ['Salt', 'Sugar', 'Honey', 'Rice'], answer: 2 },
    { q: 'A group of flamingos is called a what?', options: ['Flock', 'Flamboyance', 'Flutter', 'Flair'], answer: 1 },
    { q: 'Which planet rains diamonds, according to scientists?', options: ['Mars', 'Neptune', 'Mercury', 'Saturn'], answer: 1 },
    { q: 'What is the smallest country in the world by area?', options: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'], answer: 2 },
    { q: 'How many bones is a baby born with?', options: ['206', '270', '300', '350'], answer: 1 },
    { q: 'Which animal has fingerprints almost identical to humans?', options: ['Gorilla', 'Koala', 'Chimpanzee', 'Orangutan'], answer: 1 },
    { q: 'What is a banana botanically classified as?', options: ['Fruit', 'Berry', 'Vegetable', 'Herb'], answer: 1 },
    { q: 'A shrimp\'s heart is located in which part of its body?', options: ['Tail', 'Head', 'Middle', 'It has no heart'], answer: 1 },
    { q: 'What is the loudest animal on Earth?', options: ['Lion', 'Sperm Whale', 'Blue Whale', 'Elephant'], answer: 1 },
    { q: 'How many eyes does a bee have?', options: ['2', '3', '5', '6'], answer: 2 },
    { q: 'Which country consumes the most chocolate per person?', options: ['Belgium', 'Germany', 'Switzerland', 'USA'], answer: 2 },
    { q: 'What percentage of the human body is water?', options: ['45%', '55%', '60%', '80%'], answer: 2 },
    { q: 'How long does a day on Venus last compared to its year?', options: ['A Venusian day is shorter', 'They are equal', 'A Venusian day is longer than its year', 'Venus has no day/night cycle'], answer: 2 },
    { q: 'What is the collective name for a group of cats?', options: ['Pack', 'Clowder', 'Kindle', 'Pride'], answer: 1 },
    { q: 'How many taste buds does the average human tongue have?', options: ['1,000', '5,000', '10,000', '25,000'], answer: 2 },
    { q: 'Which fruit has more genes than a human?', options: ['Mango', 'Strawberry', 'Banana', 'Tomato'], answer: 1 },
    { q: 'A group of owls is called a what?', options: ['Flock', 'Colony', 'Parliament', 'Senate'], answer: 2 },
    { q: 'What do you call a fear of long words?', options: ['Sesquipedalophobia', 'Hippopotomonstrosesquippedaliophobia', 'Logophobia', 'Verbatophobia'], answer: 1 },
    { q: 'How many petals does a buttercup have?', options: ['4', '5', '6', '7'], answer: 1 },
    { q: 'What color was the first Coca-Cola?', options: ['Clear', 'Brown', 'Green', 'Caramel'], answer: 2 },
    { q: 'Which insect has the shortest lifespan as an adult?', options: ['Bee', 'Mayfly', 'Mosquito', 'Butterfly'], answer: 1 },
    { q: 'The average person walks the equivalent of how many times around the world in a lifetime?', options: ['1', '3', '5', '10'], answer: 2 },
    { q: 'Which animal never gets cancer?', options: ['Elephant', 'Naked mole rat', 'Blue whale', 'Greenland shark'], answer: 1 },
    { q: 'What is the most common blood type in the world?', options: ['A+', 'B+', 'O+', 'AB+'], answer: 2 },
    { q: 'How many strings does a standard guitar have?', options: ['4', '5', '6', '7'], answer: 2 },
    { q: 'What is the longest bone in the human body?', options: ['Spine', 'Humerus', 'Femur', 'Tibia'], answer: 2 },
    { q: 'Cleopatra lived closer in time to the Moon landing than to which?', options: ['Ancient Rome', 'The construction of the Pyramids', 'Alexander the Great', 'Julius Caesar'], answer: 1 },
    { q: 'How many muscles does it take to take one step?', options: ['50', '100', '200', '300'], answer: 2 },
    { q: 'Which planet has the most moons in our solar system?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 1 },
    { q: 'What is the most spoken language in the world by native speakers?', options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'], answer: 2 },
    { q: 'A snail can sleep for how long?', options: ['1 week', '1 month', '3 years', '5 years'], answer: 2 },
    { q: 'What percentage of the ocean has been explored by humans?', options: ['10%', '20%', '50%', '80%'], answer: 1 },
    { q: 'How many muscles does a cat have in each ear?', options: ['10', '22', '32', '48'], answer: 2 },
    { q: 'Which fruit is technically a berry according to botanists?', options: ['Strawberry', 'Raspberry', 'Watermelon', 'Cherry'], answer: 2 },
    { q: 'At what temperature does water boil at the top of Mount Everest?', options: ['80°C', '85°C', '70°C', '95°C'], answer: 2 },
    { q: 'How many bones does a shark have?', options: ['206', '0', '80', '300'], answer: 1 },
    { q: 'The human eye can distinguish how many shades of green?', options: ['100', '500', '1,000', 'More than any other color'], answer: 3 },
  ],
};
